### PR TITLE
Bump versions to use Bundle with Symfony 4

### PR DESCRIPTION
**Pull request by sergejvoronov**
Change is required to be able to use the bundle with Symfony 4

### CODE REVIEW

**Comment by tadcka** [comment]
@pamil

**Review by pamil — APPROVED** [review]

**Comment by pamil** [comment]
Thank you, Sergej! 🎉

**Comment by tadcka** [comment]
Thanks @pamil  :)

**Comment by pamil** [comment]
v1.1.0 released 🎉

**Pull request merged**
